### ISSUE TITLE
Add> Add> Not able to add new data

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#222] opened 2023-07-14 02:19 UTC

**Comment by abdulkhira1** [comment] 2023-07-19 06:32
@Anupriyabanger in which module?

**Comment by rohitrvayuz** [comment] 2023-07-19 06:33
possible duplicate of #229

**Comment by rohitrvayuz** [comment] 2023-07-20 10:49
This is workign

**Closed as completed by rohitrvayuz** 2023-07-20 10:49 UTC
Labels: Functional, Employee, Review required, app
